Algoritmo "G-Repita"
// Disciplina   : [Lógica de Programação e Java Script]
// Professor   : Jailson
// Descrição   : g)Elaborar  um  programa  que  apresente  como  resultado  o  valor  do  fatorial  dos  valores  ímpares situados na faixa numérica de 1 a 10.
// Autor(a)    : Nûbia
// Data atual  : 07/10/2022
Var
// Seção de Declarações das variáveis 


Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 


Fimalgoritmo